//Contains lists of: (1) words to correct — an array of arrays, where array[n][0] is the old word and array[n][1] is the new word; (2) words to remove; and (3) articles for each noun.
var corrections, removals, articles;

//Words to replace:
//Words to edit from vocabulary (due to misspellings, change of tense, etc.)
corrections = [
  ["“enough", "enough"],
  ["“banning", "ban"],
  ["“cured”", "cure"],
  ["“dare", "dare"],
  ["“everything", "everything"],
  ["“she", "she"],
  ["12yearold", "12-year-old"],
  ["6yearold", "6-year-old"],
  ["aca", "ACA"],
  ["acted", "act"],
  ["ad:", "ad"],
  ["agree:", "agree"],
  ["aig", "AIG"],
  ["Al-Shabbab", "Al-Shabbab"],
  ["all:", "all"],
  ["allows", "allow"],
  ["alltime", "all-time"],
  ["alshabaab", "Al-Shabaab"],
  ["alzheimer's", "Alzheimer's Disease"],
  ["alzheimer's", "Alzheimer's Disease"],
  ["amendment]", "amendment"],
  ["americans", "Americans"],
  ["americans", "Americans"],
  ["americans'", "Americans'"],
  ["amnesty:", "amnesty"],
  ["answering", "answer"],
  ["appears", "appear"],
  ["arrested", "arrest"],
  ["asked:", "ask"],
  ["asking", "ask"],
  ["asking", "ask"],
  ["asking", "ask"],
  ["attacked", "attack"],
  ["attacking", "attack"],
  ["attacks", "attack"],
  ["autism:", "autism"],
  ["bailed", "bailed out"],
  ["becomes", "become"],
  ["begins", "begin"],
  ["begins", "begin"],
  ["behindthescenes", "behind-the-scenes"],
  ["believes", "believe"],
  ["bernie's", "Bernie's"],
  ["bernie's", "Bernie's"],
  ["better”", "better"],
  ["biden", "Joe Biden"],
  ["big:", "big"],
  ["bluffs", "bluff"],
  ["boldness”", "boldness"],
  ["box”", "box"],
  ["call:", "call"],
  ["called", "call"],
  ["campaign:", "campaign"],
  ["campaign:", "campaign"],
  ["candidateon", "candidate"],
  ["captures", "capture"],
  ["carolina", "South Carolina"],
  ["carolina:", "South Carolina"],
  ["carolinians", "Carolinians"],
  ["cbs", "CBS"],
  ["ceo", "CEO"],
  ["ceos", "CEOs"],
  ["charges", "charge"],
  ["cheatswith", "cheat"],
  ["checks", "check"],
  ["choice:", "choice"],
  ["choiceand", "choice"],
  ["choosing", "choose"],
  ["citi", "Citi"],
  ["class:", "class"],
  ["clear:", "clear"],
  ["commander:", "Commander in Chief"],
  ["commander:", "Commander in Chief"],
  ["commercialsboring", "boring"],
  ["compete”", "compete"],
  ["concentrationbut", "concentration"],
  ["confirm:", "confirm"],
  ["confirming", "confirm"],
  ["confirms:", "confirm"],
  ["connect:", "connect"],
  ["continues", "continue"],
  ["costeffective", "cost-effective"],
  ["country:", "country"],
  ["countryare", "country"],
  ["court", "Supreme Court"],
  ["defeated", "defeat"],
  ["defeating", "defeat"],
  ["defecting", "defect"],
  ["defending", "defend"],
  ["defunded", "defund"],
  ["demands", "demand"],
  ["democrats", "Democrats"],
  ["departing", "depart"],
  ["deported", "deport"],
  ["destroying", "destroy"],
  ["discussing", "discuss"],
  ["donald", "Donald Trump"],
  ["dreams:", "dreams"],
  ["economía", "la economía"],
  ["economyand", "economy"],
  ["elected", "elect"],
  ["embarrasses", "embarrass"],
  ["enacting", "enact"],
  ["ends", "end"],
  ["enjoyed", "enjoy"],
  ["enjoying", "enjoy"],
  ["equalityand", "equality"],
  ["expected", "expect"],
  ["expectedwe", "expect"],
  ["explains", "explain"],
  ["facebook", "Facebook"],
  ["failed", "fail"],
  ["fails", "fail"],
  ["family:", "family"],
  ["feeling's", "feeling"],
  ["flashback:", "flashback"],
  ["flint's", "Flint's water"],
  ["flint's", "Flint's water problem"],
  ["force:", "force"],
  ["forwardor", "forward"],
  ["founded", "found"],
  ["fuels", "fuel"],
  ["fulltime", "full-time"],
  ["funding", "fund"],
  ["geraldo", "Geraldo Rivera"],
  ["gets", "get"],
  ["gets", "get"],
  ["getting", "get"],
  ["getting", "get"],
  ["getting", "get"],
  ["gives", "give"],
  ["glasssteagall", "Glass-Steagall"],
  ["godgiven", "God-given"],
  ["guarantees", "guarantee"],
  ["hannity", "Sean Hannity"],
  ["happened", "happen"],
  ["happens", "happen"],
  ["hardworking", "hard-working"],
  ["harmed", "harm"],
  ["having", "have"],
  ["healed", "heal"],
  ["health:", "health"],
  ["healthbut", "health"],
  ["help:", "help"],
  ["here:", "here"],
  ["here:", "here"],
  ["highquality", "high-quality"],
  ["hillary:", "Hillary"],
  ["hillary's", "Hillary's"],
  ["hillaryclinton", "Hillary Clinton"],
  ["historyi", "history"],
  ["honored", "honor"],
  ["hosting", "host"],
  ["house:", "house"],
  ["house:", "White House"],
  ["incarcerationreform", "incarceration reform"],
  ["includes", "include"],
  ["inspiration:", "inspiration"],
  ["instagram", "Instagram"],
  ["interviewed", "interview"],
  ["interviewed", "interview"],
  ["iowans", "Iowans"],
  ["iowans:", "Iowans"],
  ["jobcreating", "job-creating"],
  ["joined", "join"],
  ["joining", "join"],
  ["joins", "join"],
  ["joins", "join"],
  ["jr:", "Martin Luther King, Jr."],
  ["judgmentyou", "judgment"],
  ["justices", "Supreme Court Justices"],
  ["kicked", "kick"],
  ["kicks", "kick"],
  ["killed", "kill"],
  ["killed", "kill"],
  ["king's", "Martin Luther King's"],
  ["knocked", "knock"],
  ["knocking", "knock"],
  ["know:", "know"],
  ["knows", "know"],
  ["knows", "know"],
  ["landand", "land"],
  ["launched", "launch"],
  ["leadpoisoned", "lead-poisoned"],
  ["leadpoisoned", "lead-poisoned"],
  ["leadpoisoning", "lead poisoning"],
  ["leftwing", "left-wing"],
  ["legacy:", "legacy"],
  ["legacyand", "legacy"],
  ["lgbt", "LGBT"],
  ["lifting", "lift"],
  ["live:", "live"],
  ["looking", "look"],
  ["looking", "look"],
  ["looks", "look"],
  ["loserstrue", "losers"],
  ["loves", "love"],
  ["lowincome", "low-income"],
  ["lowincome", "low-income"],
  ["makeorbreak", "make-or-break"],
  ["makes", "make"],
  ["masacre", "massacre"],
  ["matterit", "matter"],
  ["matters:", "matter"],
  ["mccain", "John McCain"],
  ["medicareforall", "Medicare for all"],
  ["messbig", "mess"],
  ["mexicans", "Mexicans"],
  ["mexicans", "Mexicans"],
  ["middleclass", "middle-class"],
  ["mlk", "MLK"],
  ["mlk's", "MLK's"],
  ["mlk’s", "MLK's"],
  ["mongering", "fear-mongering"],
  ["msnbc", "MSNBC"],
  ["muslims", "Muslims"],
  ["muslims", "Muslims"],
  ["nafta", "NAFTA"],
  ["nastytowards", "nasty"],
  ["nation:", "nation"],
  ["needed", "need"],
  ["nevadans", "Nevadans"],
  ["news:", "news"],
  ["nh", "NH"],
  ["nh", "NH"],
  ["now:", "now"],
  ["nra's", "NRA"],
  ["numbers:", "numbers"],
  ["nyjets", "NY Jets"],
  ["obama", "Obama"],
  ["obama", "Obama"],
  ["online:", "online"],
  ["operating", "operate"],
  ["opposed", "oppose"],
  ["opposes", "oppose"],
  ["overflowing", "overflow"],
  ["overturned", "overturn"],
  ["owned", "own"],
  ["owns", "own"],
  ["panelsand", "panels"],
  ["papersnot", "papers"],
  ["pays", "pay"],
  ["peoplepowered", "people-powered"],
  ["photos:", "photos"],
  ["played", "play"],
  ["playing", "play"],
  ["plays", "play"],
  ["poor”", "poor"],
  ["possessing", "possess"],
  ["presidencyit’s", "presidency"],
  ["president:", "president"],
  ["preventing", "prevent"],
  ["preview:", "preview"],
  ["progress:", "progress"],
  ["progressnot", "progress"],
  ["promise:", "promise"],
  ["prosecuted", "prosecute"],
  ["protesting", "protest"],
  ["provides", "provide"],
  ["pushes", "push"],
  ["puts", "put"],
  ["reached", "reach"],
  ["read:", "read"],
  ["realizes", "realize"],
  ["received:", "receive"],
  ["reestablishing", "reestablish"],
  ["refuses", "refuse"],
  ["remembered", "remember"],
  ["reminded", "remind"],
  ["repealed", "repeal"],
  ["repealing", "repeal"],
  ["reported", "report"],
  ["representatives", "House of Representatives"],
  ["representing", "represent"],
  ["republicans", "Republicans"],
  ["responders", "first responders"],
  ["responding", "respond"],
  ["returned", "return"],
  ["reuters", "Reuters"],
  ["reversing", "reverse"],
  ["rhetoric;", "rhetoric"],
  ["right:", "right"],
  ["rightno", "right"],
  ["rights:", "rights"],
  ["rights”", "rights"],
  ["rightsand", "rights"],
  ["rightwing", "right-wing"],
  ["rnc", "RNC"],
  ["robertson", "Pat Robertson"],
  ["robertson:", "Pat Robertson"],
  ["room:", "room"],
  ["saeed", "bin-Saeed"],
  ["saudi", "Saudi"],
  ["say:", "say"],
  ["searched", "search"],
  ["selffunding", "self-fund"],
  ["shares", "share"],
  ["shares", "share"],
  ["sharing", "share"],
  ["shot”", "shot"],
  ["shows", "show"],
  ["shows", "show"],
  ["signed", "sign"],
  ["singlepayer", "single-payer"],
  ["smokes", "smoke"],
  ["spoiler:", "spoiler"],
  ["spreading", "spread"],
  ["starts", "start"],
  ["statement:", "statement"],
  ["story:", "story"],
  ["strugglesand", "struggles"],
  ["supported", "support"],
  ["supports", "support"],
  ["supports", "support"],
  ["takes", "take"],
  ["takes", "take"],
  ["talked", "talk"],
  ["talking", "talk"],
  ["talking", "talk"],
  ["talking", "talk"],
  ["tells", "tell"],
  ["tells", "tell"],
  ["terrifies", "terrify"],
  ["thinks", "think"],
  ["threatens", "threaten"],
  ["times", "many times"],
  ["tomorrow:", "tomorrow"],
  ["toobigto", "too big to fail"],
  ["touches", "touch"],
  ["trail:", "trail"],
  ["treated", "treat"],
  ["trump", "Trump"],
  ["trump:", "Trump"],
  ["truth:", "truth"],
  ["truth2/2", "truth"],
  ["tuitionfree", "tuition-free"],
  ["turned", "turn"],
  ["types", "types of"],
  ["values”", "values"],
  ["victimsincluding", "victims"],
  ["video:", "video"],
  ["video:", "video"],
  ["volunteer:", "volunteer"],
  ["waging", "wag"],
  ["waiting", "wait"],
  ["walmart", "Wal-Mart"],
  ["wanted", "want"],
  ["wants", "want"],
  ["wants", "want"],
  ["watch:", "watch"],
  ["watch:", "watch"],
  ["watched", "watch"],
  ["watching", "watch"],
  ["way:", "way"],
  ["week:", "week"],
  ["whoopi", "Whoopi Goldberg"],
  ["widens", "widen"],
  ["wooed", "woo"],
  ["worker’s", "worker's rights"],
  ["wrongit", "wrong"],
  ["wsj/nbc", "WSJ/NBC"],
  ["yearand", "year"],
  ["york", "New York"],
  ["yorkers", "New Yorkers"],
  ["sunday", "Sunday"],
  ["monday", "Monday"],
  ["may", "May"],
  ["tuesday", "Tuesday"],
  ["saturday", "Saturday"],
  ["wednesday", "Wednesday"],
  ["cnn", "CNN"],
  ["\"attacking", "attack"],
  ["\"bush\"", "Bush"],
  ["\"going", "go"],
  ["\"i", "I"],
  ["\"isis", "ISIS"],
  ["\"natural", "natural"],
  ["\"schlonged\"", "schlong"],
  ["\"stiff\"", "stiff"],
  ["\"stinky\"", "stinky"],
  ["\"ted", "Ted Cruz"],
  ["\"that", "that"],
  ["\"the", "the"],
  ["\"we", "we"],
  ["\"why", "why"],
  ["\"wrong", "wrong"],
  ["hillary", "Hillary Clinton"],
  ["clinton", "Hillary Clinton"],
  ["bush", "Jeb Bush"],
  ["jeb", "Jeb Bush"],
  ["trump", "Donald Trump"],
  ["donald", "Donald Trump"],
  ["ted", "Ted Cruz"],
  ["cruz", "Ted Cruz"],
  ["bernie", "Bernie Sanders"],
  ["sanders", "Bernie Sanders"],
  ["$100000", "$100,000"],
  ["$13000", "$13,000"],
  ["$4", "$4"],
  ["abandoning", "abandon"],
  ["affording", "afford"],
  ["allowing", "allow"],
  ["apology…", "apology"],
  ["applies", "apply"],
  ["asked", "ask"],
  ["attempts", "attempt"],
  ["babyand", "baby"],
  ["sanders’", "Bernie Sanders'"],
  ["carewithout", "care"],
  ["‘cataclysmic’", "cataclysmic"],
  ["celebratingbill", "celebrate"],
  ["cheering", "cheer"],
  ["collecting", "collect"],
  ["confirms", "confirm"],
  ["counting", "count"],
  ["“cut", "cut"],
  ["demanded", "demand"],
  ["deporting", "deport"],
  ["destroyed", "destroy"],
  ["earned", "earn"],
  ["electing", "elect"],
  ["end;", "end"],
  ["endorses", "endorse"],
  ["establishing", "establish"],
  ["terriblefumbled", "fumble"],
  ["governmentunless", "government"],
  ["grandmaplus", "grandma"],
  ["hijacked", "hijack"],
  ["hurting", "hurt"],
  ["invented", "invent"],
  ["is…", "is"],
  ["law”", "law"],
  ["leads", "lead"],
  ["leadershipnot", "leadership"],
  ["lobbyperiod", "lobby"],
  ["man”", "man"],
  ["matters", "matter"],
  ["misled", "mislead"],
  ["missed", "miss"],
  ["moneyit's", "money"],
  ["nightmarejon", "nightmare"],
  ["out”", "out"],
  ["overruns", "overrun"],
  ["overturning", "overturn"],
  ["politician…", "politician"],
  ["polltrump", "poll"],
  ["recorded", "record"],
  ["recruiting", "recruit"],
  ["reforming", "reform"],
  ["religion;", "religion"],
  ["represented", "represent"],
  ["resurrecting", "resurrect"],
  ["retires", "retire"],
  ["robs", "rob"],
  ["seems", "seem"],
  ["seems", "seem"],
  ["slams", "slam"],
  ["spewing", "spew"],
  ["starting", "start"],
  ["storiessome", "stories"],
  ["storywant", "story"],
  ["streetand", "street"],
  ["surpassed", "surpass"],
  ["suspected", "suspect"],
  ["throwing", "throw"],
  ["ticket”", "ticked"],
  ["“today", "today"],
  ["bigtofail”", "too-big-to-fail"],
  ["toughbut", "tough"],
  ["tower”", "tower"],
  ["transformed", "transform"],
  ["treating", "treat"],
  ["tuitionthat's", "tuition"],
  ["tweetwhile", "tweet"],
  ["upsets", "upset"],
  ["valuesthat's", "values"],
  ["visiting", "visit"],
  ["wielding", "wield"],
  ["wishing", "wish"],
  ["wolfeboro", "Wolfeboro"],
  ["treats", "treat"],
  ["2pm", "at 2pm"],
  ["alzheimer’s", "Alzheimer's Disease"],
  ["chozick", "Amy Chozick"],
  ["barack", "Barack Obama"],
  ["schlonged", "being schlonged"],
  ["bullying”", "bullying"],
  ["citigroup", "Citigroup"],
  ["citizens", "Citizens United"],
  ["citizens", "Citizens United"],
  ["cnn/wmur", "CNN"],
  ["commanderinchief", "Commander in Chief"],
  ["costofliving", "cost of living"],
  ["dnc", "DNC"],
  ["doddfrank", "Dodd-Frank"],
  ["candidato", "el candidato"],
  ["yihadismo", "el yihadismo"],
  ["everyonenot", "everyone"],
  ["flint’s", "Flint's water"],
  ["gopville", "GOPville"],
  ["grammyaward", "Grammy Award"],
  ["clinton”", "Hillary Clinton"],
  ["historyor", "history"],
  ["internet", "Internet"],
  ["welch​", "Jack Welch"],
  ["kwanzaa", "Kwanzaa"],
  ["salud", "la salud"],
  ["merch", "merch"],
  ["eastthat's", "Middle East"],
  ["oped", "Op-Ed"],
  ["robertson​", "Pat Robertson"],
  ["quinnipiac", "Quinnipiac Poll"],
  ["ramadi", "Ramadi"],
  ["adelson", "Sheldon Adelson"],
  ["toobigtofail", "Too big to fail"],
  ["tpp", "TPP"],
  ["buffett", "Warren Buffett"],
  ["estudiante", "estudiantes"],
  ["guns”", "guns"],
  ["kidsnot", "kids"],
  ["problemas", "los problemas"],
  ["cruz'", "Ted Cruz's"],
  ["year’s", "year's"],
  ["36%", "36% of"],
  ["50year", "50-year"],
  ["60%", "60% of"],
  ["62%", "62% of"],
  ["75%", "75% of"],
  ["94%", "94% of"],
  ["woman’s", "a woman's"],
  ["africanamerican", "African-American"],
  ["america'", "America's"],
  ["america", "America"],
  ["america's", "America's"],
  ["baby's", "baby's"],
  ["bernie’s", "Bernie Sanders'"],
  ["chestbeating", "chest-beating"],
  ["criminalization", "climinalization of"],
  ["coalburning", "coal-burning"],
  ["democrats'", "Democrats'"],
  ["trump’s", "Donald Trump's"],
  ["“equal", "equal"],
  ["forprofit", "for-profit"],
  ["headtohead", "head-to-head"],
  ["highspeed", "high-speed"],
  ["clinton's", "Hillary Clinton's"],
  ["hillary’s", "Hillary Clinton's"],
  ["insidethebeltway", "inside-the-beltway"],
  ["jeb's", "Jeb Bush's"],
  ["neverending", "never-ending"],
  ["npr's", "NPR's"],
  ["nra’s", "NRA's"],
  ["onetenth", "one-tenth"],
  ["orwellian", "Orwellian"],
  ["postdebate", "post-debate"],
  ["relaxing", "relaxing"],
  ["republicanled", "Republican-led"],
  ["saferbecause", "safer"],
  ["sameold", "same old"],
  ["“palin’s'", "Sarah Palin's"],
  ["palin's", "Sarah Palin's"],
  ["palin's", "Sarah Palin's"],
  ["secondlargest", "second-largest"],
  ["sixthyear", "sixth-year"],
  ["smaller", "smaller"],
  ["trickledown", "trickle-down"],
  ["workers’", "workers’"],
  ["worldclass", "world-class"]
];


//Words to remove:
removals = [
  "remove",
  ":",
  "'08",
  "“an",
  "“as",
  "“bottom",
  "“do",
  "“family",
  "“i",
  "“i'm",
  "“i’ll'",
  "“it’s",
  "“no”",
  "“this",
  "“what",
  "[14th",
  "[hillary]",
  "→'",
  ">",
  "$",
  "$'s",
  "$118500",
  "$11m",
  "$15",
  "$150",
  "$1m",
  "$200",
  "$28",
  "$35000000",
  "$40",
  "$487k",
  "$5",
  "$50000",
  "$5807",
  "$59",
  "$6",
  "$63000000",
  "$9400",
  "$millions",
  "1",
  "1/2",
  "10",
  "10%",
  "100",
  "100",
  "10000",
  "103",
  "108",
  "10bad",
  "11:30",
  "11:35pme",
  "11:50",
  "114",
  "12yearold",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "1988",
  "19yearold",
  "1st",
  "2",
  "2/2",
  "20",
  "2008",
  "2015",
  "2016",
  "2016",
  "2016",
  "2017",
  "21%",
  "21st",
  "25k",
  "27",
  "28",
  "3",
  "3",
  "30",
  "35",
  "39",
  "4",
  "4",
  "4",
  "4",
  "45",
  "46",
  "46%",
  "47246",
  "5",
  "50",
  "5000",
  "53:5",
  "58",
  "5pm",
  "5pm",
  "6",
  "6",
  "62",
  "6yearold”",
  "7",
  "7:00",
  "75000",
  "8",
  "8",
  "8:00",
  "9",
  "96",
  "9pm",
  "9pm",
  "acanot",
  "act”",
  "ain’t",
  "americans'",
  "anotheri'm",
  "anymore",
  "appointmentswe",
  "are\"",
  "arrestado",
  "atención",
  "autismthey",
  "bernie's",
  "booketc",
  "campaignhis",
  "can’t",
  "cillizza",
  "commercialsboring",
  "cruz's",
  "ct:",
  "cties",
  "daughterread:",
  "deber",
  "derecho",
  "doand",
  "doesn’t",
  "don't",
  "don't",
  "don’t",
  "don’t",
  "dono",
  "drehle",
  "duked",
  "ERE ARE THE WORDS FOR @ TedCruz : [ '",
  "eso",
  "et:",
  "expectedwe",
  "extraño",
  "family's",
  "fayde",
  "flint's",
  "for:",
  "fuma",
  "garantizan",
  "gotv",
  "greati",
  "hacer",
  "happen”",
  "harder”",
  "haven’t",
  "haven’t",
  "havn't",
  "he's",
  "here's",
  "hija",
  "him:",
  "hint:",
  "hrc",
  "hundreds",
  "I've",
  "i’m",
  "i’ve",
  "icymi",
  "in:",
  "interestsonly",
  "iowa/nh/sc",
  "isn't",
  "isn't",
  "it:",
  "it:",
  "it's",
  "it”",
  "itnot",
  "jusr",
  "las",
  "leaderswe",
  "let's",
  "libres",
  "line:",
  "los",
  "lows",
  "mariguana",
  "mcquaid",
  "me:",
  "médica",
  "merch:",
  "muchacho",
  "muy",
  "naciones",
  "nationno",
  "night's",
  "numberd",
  "nyt",
  "obama's",
  "on:",
  "one's",
  "overincentive",
  "packed",
  "parece",
  "people's",
  "perdió",
  "permitir",
  "person”",
  "personal”",
  "pharma",
  "placenow",
  "podemos",
  "podemos",
  "poll:",
  "poll:trump",
  "prek",
  "presidencyit’s",
  "president's",
  "presidente",
  "presidentit's",
  "privilegio",
  "psst:",
  "reportingand",
  "reps",
  "rpvirginia",
  "sakran",
  "same:",
  "saturday:",
  "seguro",
  "shoker",
  "sidewho's",
  "sigan",
  "siguen",
  "snyder's",
  "st:",
  "starters",
  "sucediendo",
  "system”",
  "tedfree",
  "that’s",
  "thatand",
  "thembut",
  "there’s",
  "thousands",
  "threatit",
  "thx",
  "tiene",
  "tipo",
  "today:",
  "todos",
  "tonight:",
  "tonight's",
  "toybut",
  "trump's",
  "truth2/2",
  "tweetsvery",
  "unirnos",
  "us:",
  "utterly",
  "virginia's",
  "von",
  "w/",
  "w/",
  "w/him",
  "w/me",
  "wayne's",
  "we're",
  "we're",
  "we're",
  "we’ll",
  "we’re",
  "we’re",
  "we’ve",
  "we’ve",
  "wellwith",
  "what’s",
  "who’ve",
  "wife's",
  "win:",
  "woman's",
  "women's",
  "women's",
  "won't",
  "won't",
  "won't",
  "won't",
  "won’t",
  "world's",
  "would've",
  "year's",
  "years",
  "you’ll",
  "you’re",
  "you’re",
  "zero'",
  "\"a",
  "$\'s",
  "alshabbab",
  "adjective",
  "he’s",
  "isn't",
  "would've",
  "anotheri'm",
  "verb (usu participle)",
  "oped:",
  "país",
  "it's",
  "$400m/year",
  "$50",
  "$80",
  "$89",
  "08",
  "+/",
  "11",
  "150",
  "15k",
  "18000000",
  "1984",
  "2%",
  "21",
  "21points",
  "3%",
  "37",
  "39%",
  "5k",
  "6700000",
  "747",
  "9:30pme",
  "$50",
  "$80",
  "$89",
  "08",
  "+/",
  "11",
  "1130",
  "1135pme",
  "1150",
  "15k",
  "18000000",
  "1984",
  "2%",
  "21",
  "21points",
  "3%",
  "37",
  "39%",
  "5k",
  "6700000",
  "700",
  "800",
  "alongno",
  "vs",
  "wapo",
  "would’ve",
  "yearbut",
  "$1",
  "$100",
  "$18m",
  "$55",
  "11",
  "112",
  "2025",
  "33000",
  "38",
  "48",
  "524",
  "54",
  "89399",
  "adicción",
  "anotheri’m",
  "arewe",
  "are”",
  "away”",
  "colegiatura",
  "cárcel",
  "cómo",
  "debería",
  "diferencia",
  "elección",
  "entiende",
  "estamos",
  "experiencia",
  "isn’t",
  "it’s",
  "liderazgo",
  "mantenernos",
  "mantenido",
  "million$37m",
  "necesitamos",
  "nelba",
  "nuestros",
  "odiosas",
  "ones",
  "otros",
  "pagar",
  "países",
  "préstamo",
  "sabe",
  "segurosella",
  "serio",
  "she’s",
  "shouldering",
  "shouldn’t",
  "substituto",
  "thatwe",
  "trabajar",
  "tratar",
  "valores",
  "wasn’t",
  "“there",
  "$1000",
  "“i’ll",
  "“i’m",
  "“too'",
  "qa",
  "¯_ツ_/¯",
  "“cruz",
  "maga",
  "meaningtell",
  "mondale/ferraro",
  "workingand",
  "$56",
  "$6240",
  "/",
  "105",
  "11",
  "12",
  "1400+",
  "16th",
  "25",
  "2513665",
  "3200",
  "40",
  "43",
  "76",
  "78",
  "89",
  "92",
  "95",
  "dhs'",
  "didn’t",
  "**HERE ARE THE ~800 MOST RECENT WORDS FOR*** TedCruz [ '",
  "mcmanamon",
  "schlafly",
  "**HERE ARE THE ~800 MOST RECENT WORDS FOR*** HillaryClinton [ '",
  "ningún",
  "mckinnon",
  "**HERE ARE THE ~800 MOST RECENT WORDS FOR*** BernieSanders [ '",
  "sununu",
  "here’s",
  "here’s",
  "powering",
  "she’s",
  "where’s",
  "ingredion's",
  "let’s",
  "bakken",
  "bilbray",
  "cafta",
  "naral",
  "pntr",
  "privateforprofit"
];

nounProperties = [
  {
    word: "opinion",
    articles: ["my", "your", "an"],
    person: "third"
  },
  {
    word: "paper",
    articles: []
    person: "third"
  },
  {
    word: "advice",
    articles: ["test", "the"]
    person: "third"
  },
  {
    word: "Americans",
    articles: []
    person: "plural"
  }
];
